export const PAGE_DETAILS_REQUEST = "PAGE_DETAILS_REQUEST";
export const PAGE_DETAILS_SUCCESS = "PAGE_DETAILS_SUCCESS";
export const PAGE_DETAILS_FAIL = "PAGE_DETAILS_FAIL";

export const PAGE_UPDATE_REQUEST = "PAGE_UPDATE_REQUEST";
export const PAGE_UPDATE_SUCCESS = "PAGE_UPDATE_SUCCESS";
export const PAGE_UPDATE_FAIL = "PAGE_UPDATE_FAIL";
export const PAGE_UPDATE_RESET = "PAGE_UPDATE_RESET";
